apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    name: webserver
spec:
  selector:
    matchLabels:
      app: webserver
      role: webserver
  replicas: 2
  template:
    metadata:
      labels:
        app: webserver
        role: webserver
    spec:
      containers:
      - name: webserver
        image: httpd:2.4
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  selector:
    app: webserver
  ports:
  - port: 80
    targetPort: 80
