apiVersion: v1
kind: Pod
metadata:
  name: phpBack
  labels:
    name: phpBack
spec:
  containers:
  - name: phpBack
    image: php:7.2-apache
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
